"""feat: add WORLDOS core domain model

Revision ID: 3c781302d674
Revises: 1
Create Date: 2026-08-18 14:49:38.024244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c781302d674'
down_revision = '1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worlds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('seed', sa.String(), nullable=False),
    sa.Column('current_tick', sa.Integer(), nullable=False),
    sa.Column('simulation_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('wealth', sa.Float(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('food_supply', sa.Float(), nullable=False),
    sa.Column('unrest', sa.Float(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('factions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('ideology', sa.String(), nullable=False),
    sa.Column('wealth', sa.Float(), nullable=False),
    sa.Column('power', sa.Float(), nullable=False),
    sa.Column('leader_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['leader_id'], ['characters.id'], name='fk_faction_leader_id', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=False),
    sa.Column('total_supply', sa.Float(), nullable=False),
    sa.Column('total_demand', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('occupation', sa.String(), nullable=False),
    sa.Column('wealth', sa.Float(), nullable=False),
    sa.Column('health', sa.Float(), nullable=False),
    sa.Column('city_id', sa.UUID(), nullable=True),
    sa.Column('faction_id', sa.UUID(), nullable=True),
    sa.Column('personality_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('economic_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('buyer_type', sa.String(), nullable=False),
    sa.Column('seller_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_value', sa.Float(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_economic_transactions_buyer_id'), 'economic_transactions', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_economic_transactions_seller_id'), 'economic_transactions', ['seller_id'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('city_id', sa.UUID(), nullable=True),
    sa.Column('faction_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parent_event_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['faction_id'], ['factions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_actor_id'), 'events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_events_target_id'), 'events', ['target_id'], unique=False)
    op.create_table('inventories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventories_owner_id'), 'inventories', ['owner_id'], unique=False)
    op.create_table('goals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('target_information', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('summary', sa.String(), nullable=False),
    sa.Column('importance', sa.Float(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('related_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_character_id', sa.UUID(), nullable=False),
    sa.Column('target_character_id', sa.UUID(), nullable=False),
    sa.Column('trust', sa.Float(), nullable=False),
    sa.Column('respect', sa.Float(), nullable=False),
    sa.Column('fear', sa.Float(), nullable=False),
    sa.Column('friendship', sa.Float(), nullable=False),
    sa.Column('hostility', sa.Float(), nullable=False),
    sa.Column('influence', sa.Float(), nullable=False),
    sa.CheckConstraint('source_character_id != target_character_id', name='chk_no_self_relationship'),
    sa.ForeignKeyConstraint(['source_character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_character_id', 'target_character_id', name='uq_relationship_source_target')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('relationships')
    op.drop_table('memories')
    op.drop_table('goals')
    op.drop_index(op.f('ix_inventories_owner_id'), table_name='inventories')
    op.drop_table('inventories')
    op.drop_index(op.f('ix_events_target_id'), table_name='events')
    op.drop_index(op.f('ix_events_actor_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_economic_transactions_seller_id'), table_name='economic_transactions')
    op.drop_index(op.f('ix_economic_transactions_buyer_id'), table_name='economic_transactions')
    op.drop_table('economic_transactions')
    op.drop_table('characters')
    op.drop_table('resources')
    op.drop_table('factions')
    op.drop_table('cities')
    op.drop_table('worlds')
    # ### end Alembic commands ###
