"""feat: add belief and decision records

Revision ID: af9a2af3e84d
Revises: 3c781302d674
Create Date: 2026-08-24 17:19:19.079473

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af9a2af3e84d'
down_revision = '3c781302d674'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_decisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('world_id', sa.UUID(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('decision_summary', sa.String(), nullable=False),
    sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('latency', sa.Float(), nullable=False),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['characters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['world_id'], ['worlds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('beliefs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('subject_type', sa.String(), nullable=False),
    sa.Column('belief_type', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key('fk_faction_leader_id', 'factions', 'characters', ['leader_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.add_column('memories', sa.Column('source_event_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'memories', 'events', ['source_event_id'], ['id'], ondelete='SET NULL')
    op.add_column('relationships', sa.Column('obligation', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relationships', 'obligation')
    op.drop_constraint(None, 'memories', type_='foreignkey')
    op.drop_column('memories', 'source_event_id')
    op.drop_constraint('fk_faction_leader_id', 'factions', type_='foreignkey')
    op.drop_table('beliefs')
    op.drop_table('agent_decisions')
    # ### end Alembic commands ###
